const allPlayers = [
  // GOALKEEPERS (36)
  { name: "Emiliano Martinez", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Emiliano_Mart%C3%ADnez_2022_%28cropped%29.jpg/440px-Emiliano_Mart%C3%ADnez_2022_%28cropped%29.jpg" },
  { name: "Victor Valdes", position: "GK", img: "https://via.placeholder.com/150?text=Valdes" },
  { name: "Manuel Neuer", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Manuel_Neuer_2019-06-07.jpg/440px-Manual_Neuer_2019-06-07.jpg" },
  { name: "Ter Stegen", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Marc-Andr%C3%A9_ter_Stegen_2022.jpg/440px-Marc-Andr%C3%A9_ter_Stegen_2022.jpg" },
  { name: "Oliver Kahn", position: "GK", img: "https://via.placeholder.com/150?text=Kahn" },
  { name: "Thibaut Courtois", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Thibaut_Courtois_2018.jpg/440px-Thibaut_Courtois_2018.jpg" },
  { name: "Dida", position: "GK", img: "https://via.placeholder.com/150?text=Dida" },
  { name: "Gigi Donnarumma", position: "GK", img: "https://via.placeholder.com/150?text=Donnarumma" },
  { name: "Gigi Buffon", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Gianluigi_Buffon_2017.jpg/440px-Gianluigi_Buffon_2017.jpg" },
  { name: "Allison Becker", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Alisson_Becker_2018.jpg/440px-Alisson_Becker_2018.jpg" },
  { name: "Ederson", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Ederson_Moraes_2019.jpg/440px-Ederson_Moraes_2019.jpg" },
  { name: "David De Gea", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/David_de_Gea_2018.jpg/440px-David_de_Gea_2018.jpg" },
  { name: "Van Der Sar", position: "GK", img: "https://via.placeholder.com/150?text=VanDerSar" },
  { name: "David Raya", position: "GK", img: "https://via.placeholder.com/150?text=Raya" },
  { name: "Iker Casillas", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Iker_Casillas_Euro_2012_vs_Italy_01.jpg/440px-Iker_Casillas_Euro_2012_vs_Italy_01.jpg" },
  { name: "Sommer", position: "GK", img: "https://via.placeholder.com/150?text=Sommer" },
  { name: "Yasin Bonou", position: "GK", img: "https://via.placeholder.com/150?text=Bounou" },
  { name: "Livakovich", position: "GK", img: "https://via.placeholder.com/150?text=Livakovic" },
  { name: "Hugo Loris", position: "GK", img: "https://via.placeholder.com/150?text=Lloris" },
  { name: "Mike Maignan", position: "GK", img: "https://via.placeholder.com/150?text=Maignan" },
  { name: "Lev Yashin", position: "GK", img: "https://via.placeholder.com/150?text=Yashin" },
  { name: "Peter Schemichel", position: "GK", img: "https://via.placeholder.com/150?text=Schmeichel" },
  { name: "Dinor Zoff", position: "GK", img: "https://via.placeholder.com/150?text=Zoff" },
  { name: "Peter Cech", position: "GK", img: "https://via.placeholder.com/150?text=Cech" },
  { name: "Jan Oblak", position: "GK", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Jan_Oblak_2017.jpg/440px-Jan_Oblak_2017.jpg" },
  { name: "Gregor Kobel", position: "GK", img: "https://via.placeholder.com/150?text=Kobel" },
  { name: "Unai Simon", position: "GK", img: "https://via.placeholder.com/150?text=Simon" },
  { name: "Jordan Pickford", position: "GK", img: "https://via.placeholder.com/150?text=Pickford" },
  { name: "Schzency", position: "GK", img: "https://via.placeholder.com/150?text=Szczesny" },
  { name: "Diago Costa", position: "GK", img: "https://via.placeholder.com/150?text=Costa" },
  { name: "Andre Onana", position: "GK", img: "https://via.placeholder.com/150?text=Onana" },
  { name: "Kepa", position: "GK", img: "https://via.placeholder.com/150?text=Kepa" },
  { name: "Lenin", position: "GK", img: "https://via.placeholder.com/150?text=Leno" },
  { name: "Robert Sanchez", position: "GK", img: "https://via.placeholder.com/150?text=Sanchez" },
  { name: "Sachin Suresh", position: "GK", img: "https://via.placeholder.com/150?text=Sachin" },
  { name: "Gordon Banks", position: "GK", img: "https://via.placeholder.com/150?text=Banks" },
  // DEFENDERS (48)
  { name: "Harry Maguire", position: "DEF", img: "https://via.placeholder.com/150?text=Maguire" },
  { name: "John Stones", position: "DEF", img: "https://via.placeholder.com/150?text=Stones" },
  { name: "Kyle Walker", position: "DEF", img: "https://via.placeholder.com/150?text=Walker" },
  { name: "Luke Shaw", position: "DEF", img: "https://via.placeholder.com/150?text=Shaw" },
  { name: "Ashley Cole", position: "DEF", img: "https://via.placeholder.com/150?text=Cole" },
  { name: "Trent Alexander Arnold", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Trent_Alexander-Arnold_2019.jpg/440px-Trent_Alexander-Arnold_2019.jpg" },
  { name: "Carlos Alberto", position: "DEF", img: "https://via.placeholder.com/150?text=Alberto" },
  { name: "Roberto Carlos", position: "DEF", img: "https://via.placeholder.com/150?text=RCarlos" },
  { name: "Cafu", position: "DEF", img: "https://via.placeholder.com/150?text=Cafu" },
  { name: "Marquinhos", position: "DEF", img: "https://via.placeholder.com/150?text=Marquinhos" },
  { name: "Saliba", position: "DEF", img: "https://via.placeholder.com/150?text=Saliba" },
  { name: "Thiago Hernandez", position: "DEF", img: "https://via.placeholder.com/150?text=Theo" },
  { name: "Raphael Varane", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Rapha%C3%ABl_Varane_2018.jpg/440px-Rapha%C3%ABl_Varane_2018.jpg" },
  { name: "Upamecano", position: "DEF", img: "https://via.placeholder.com/150?text=Upamecano" },
  { name: "Joules Kounde", position: "DEF", img: "https://via.placeholder.com/150?text=Kounde" },
  { name: "Thuram", position: "DEF", img: "https://via.placeholder.com/150?text=Thuram" },
  { name: "Marscel Dessaily", position: "DEF", img: "https://via.placeholder.com/150?text=Desailly" },
  { name: "Carlos Puyol", position: "DEF", img: "https://via.placeholder.com/150?text=Puyol" },
  { name: "Jordi Alba", position: "DEF", img: "https://via.placeholder.com/150?text=Alba" },
  { name: "Gerrard Pique", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Gerard_Piqu%C3%A9_2018.jpg/440px-Gerard_Piqu%C3%A9_2018.jpg" },
  { name: "Sergio Ramos", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Sergio_Ramos_2017.jpg/440px-Sergio_Ramos_2017.jpg" },
  { name: "Pepe", position: "DEF", img: "https://via.placeholder.com/150?text=Pepe" },
  { name: "Jaoa Cancelo", position: "DEF", img: "https://via.placeholder.com/150?text=Cancelo" },
  { name: "Paolo Maldini", position: "DEF", img: "https://via.placeholder.com/150?text=Maldini" },
  { name: "Fabio Cannavaro", position: "DEF", img: "https://via.placeholder.com/150?text=Cannavaro" },
  { name: "Allesandro Nesta", position: "DEF", img: "https://via.placeholder.com/150?text=Nesta" },
  { name: "Franco Baresi", position: "DEF", img: "https://via.placeholder.com/150?text=Baresi" },
  { name: "Giorgio Chellini", position: "DEF", img: "https://via.placeholder.com/150?text=Chiellini" },
  { name: "Allesandro CoastCurta", position: "DEF", img: "https://via.placeholder.com/150?text=Costacurta" },
  { name: "Leornado Bonnucci", position: "DEF", img: "https://via.placeholder.com/150?text=Bonucci" },
  { name: "Virgil Vandijk", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Virgil_van_Dijk_2019.jpg/440px-Virgil_van_Dijk_2019.jpg" },
  { name: "De Ligt", position: "DEF", img: "https://via.placeholder.com/150?text=DeLigt" },
  { name: "Christian Romero", position: "DEF", img: "https://via.placeholder.com/150?text=Romero" },
  { name: "Franz Beckanbaur", position: "DEF", img: "https://via.placeholder.com/150?text=Beckenbauer" },
  { name: "Philip Lahm", position: "DEF", img: "https://via.placeholder.com/150?text=Lahm" },
  { name: "Marcelo", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Marcelo_%28cropped%29.jpg/440px-Marcelo_%28cropped%29.jpg" },
  { name: "Dani Alves", position: "DEF", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Dani_Alves_2017.jpg/440px-Dani_Alves_2017.jpg" },
  { name: "Stam", position: "DEF", img: "https://via.placeholder.com/150?text=Stam" },
  { name: "Rio Ferdinard", position: "DEF", img: "https://via.placeholder.com/150?text=Ferdinand" },
  { name: "Antonine Rudigier", position: "DEF", img: "https://via.placeholder.com/150?text=Rudiger" },
  { name: "Bobby Moor", position: "DEF", img: "https://via.placeholder.com/150?text=Moore" },
  { name: "Thiago Silva", position: "DEF", img: "https://via.placeholder.com/150?text=TSilva" },
  { name: "Matt Hummels", position: "DEF", img: "https://via.placeholder.com/150?text=Hummels" },
  { name: "Allen Hansen", position: "DEF", img: "https://via.placeholder.com/150?text=Hansen" },
  { name: "John Terry", position: "DEF", img: "https://via.placeholder.com/150?text=Terry" },
  { name: "Janis Zannetti", position: "DEF", img: "https://via.placeholder.com/150?text=Zanetti" },
  { name: "Donald Koeman", position: "DEF", img: "https://via.placeholder.com/150?text=Koeman" },
  { name: "Andy Robertson", position: "DEF", img: "https://via.placeholder.com/150?text=Robertson" },
  // MIDFIELDERS (56)
  { name: "Kroos", position: "MID", img: "https://via.placeholder.com/150?text=Kroos" },
  { name: "Modric", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Luka_Modri%C4%87_2018.jpg/440px-Luka_Modri%C4%87_2018.jpg" },
  { name: "Casemeiro", position: "MID", img: "https://via.placeholder.com/150?text=Casemiro" },
  { name: "Kaka", position: "MID", img: "https://via.placeholder.com/150?text=Kaka" },
  { name: "Guti", position: "MID", img: "https://via.placeholder.com/150?text=Guti" },
  { name: "Griezmann", position: "MID", img: "https://via.placeholder.com/150?text=Griezmann" },
  { name: "Iniesta", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Andr%C3%A9s_Iniesta_2018.jpg/440px-Andr%C3%A9s_Iniesta_2018.jpg" },
  { name: "Xavi", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Xavi_Hern%C3%A1ndez_2022_%28cropped%29.jpg/440px-Xavi_Hern%C3%A1ndez_2022_%28cropped%29.jpg" },
  { name: "Xabi", position: "MID", img: "https://via.placeholder.com/150?text=Xabi" },
  { name: "Busquets", position: "MID", img: "https://via.placeholder.com/150?text=Busquets" },
  { name: "Rice", position: "MID", img: "https://via.placeholder.com/150?text=Rice" },
  { name: "Palmer", position: "MID", img: "https://via.placeholder.com/150?text=Palmer" },
  { name: "Kevin De Bruyne", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Kevin_De_Bruyne_201807091.jpg/440px-Kevin_De_Bruyne_201807091.jpg" },
  { name: "Pogba", position: "MID", img: "https://via.placeholder.com/150?text=Pogba" },
  { name: "Pirlo", position: "MID", img: "https://via.placeholder.com/150?text=Pirlo" },
  { name: "Piero", position: "MID", img: "https://via.placeholder.com/150?text=DelPiero" },
  { name: "Gattuso", position: "MID", img: "https://via.placeholder.com/150?text=Gattuso" },
  { name: "De Jong", position: "MID", img: "https://via.placeholder.com/150?text=DeJong" },
  { name: "Rakitic", position: "MID", img: "https://via.placeholder.com/150?text=Rakitic" },
  { name: "Pele", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Pele_con_brasil.jpg/440px-Pele_con_brasil.jpg" },
  { name: "Maradona", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Maradona-Mundial_86_con_la_copa.jpg/440px-Maradona-Mundial_86_con_la_copa.jpg" },
  { name: "Ozil", position: "MID", img: "https://via.placeholder.com/150?text=Ozil" },
  { name: "Gavi", position: "MID", img: "https://via.placeholder.com/150?text=Gavi" },
  { name: "Pedri", position: "MID", img: "https://via.placeholder.com/150?text=Pedri" },
  { name: "Rodri", position: "MID", img: "https://via.placeholder.com/150?text=Rodri" },
  { name: "Bellingam", position: "MID", img: "https://via.placeholder.com/150?text=Bellingham" },
  { name: "Beckham", position: "MID", img: "https://via.placeholder.com/150?text=Beckham" },
  { name: "Zidane", position: "MID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg/440px-Zinedine_Zidane_by_Tasnim_03.jpg" },
  { name: "Mac Allister", position: "MID", img: "https://via.placeholder.com/150?text=MacAllister" },
  { name: "Mashcerano", position: "MID", img: "https://via.placeholder.com/150?text=Mascherano" },
  { name: "Mathaus", position: "MID", img: "https://via.placeholder.com/150?text=Matthaus" },
  { name: "Steven Gerrard", position: "MID", img: "https://via.placeholder.com/150?text=Gerrard" },
  { name: "Lampard", position: "MID", img: "https://via.placeholder.com/150?text=Lampard" },
  { name: "Zico", position: "MID", img: "https://via.placeholder.com/150?text=Zico" },
  { name: "Baggio", position: "MID", img: "https://via.placeholder.com/150?text=Baggio" },
  { name: "Viera", position: "MID", img: "https://via.placeholder.com/150?text=Vieira" },
  { name: "Scholes", position: "MID", img: "https://via.placeholder.com/150?text=Scholes" },
  { name: "Kante", position: "MID", img: "https://via.placeholder.com/150?text=Kante" },
  { name: "Verratti", position: "MID", img: "https://via.placeholder.com/150?text=Verratti" },
  { name: "Juninho", position: "MID", img: "https://via.placeholder.com/150?text=Juninho" },
  { name: "Platini", position: "MID", img: "https://via.placeholder.com/150?text=Platini" },
  { name: "Cruyff", position: "MID", img: "https://via.placeholder.com/150?text=Cruyff" },
  { name: "Gullit", position: "MID", img: "https://via.placeholder.com/150?text=Gullit" },
  { name: "Stefano", position: "MID", img: "https://via.placeholder.com/150?text=DiStefano" },
  { name: "Rijkaard", position: "MID", img: "https://via.placeholder.com/150?text=Rijkaard" },
  { name: "Makalele", position: "MID", img: "https://via.placeholder.com/150?text=Makelele" },
  { name: "Socrates", position: "MID", img: "https://via.placeholder.com/150?text=Socrates" },
  { name: "Keane", position: "MID", img: "https://via.placeholder.com/150?text=Keane" },
  { name: "Toure", position: "MID", img: "https://via.placeholder.com/150?text=Toure" },
  { name: "Valverade", position: "MID", img: "https://via.placeholder.com/150?text=Valverde" },
  { name: "Odegaard", position: "MID", img: "https://via.placeholder.com/150?text=Odegaard" },
  { name: "Muller", position: "MID", img: "https://via.placeholder.com/150?text=Muller" },
  { name: "Sneijder", position: "MID", img: "https://via.placeholder.com/150?text=Sneijder" },
  { name: "Deco", position: "MID", img: "https://via.placeholder.com/150?text=Deco" },
  { name: "Giggs", position: "MID", img: "https://via.placeholder.com/150?text=Giggs" },
  { name: "Okocha", position: "MID", img: "https://via.placeholder.com/150?text=Okocha" },
  // FORWARDS (51)
  { name: "Raul", position: "FWD", img: "https://via.placeholder.com/150?text=Raul" },
  { name: "Totti", position: "FWD", img: "https://via.placeholder.com/150?text=Totti" },
  { name: "Sanchez", position: "FWD", img: "https://via.placeholder.com/150?text=Sanchez" },
  { name: "Berkamp", position: "FWD", img: "https://via.placeholder.com/150?text=Bergkamp" },
  { name: "David Villa", position: "FWD", img: "https://via.placeholder.com/150?text=Villa" },
  { name: "Kane", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Harry_Kane_2018.jpg/440px-Harry_Kane_2018.jpg" },
  { name: "Richarlison", position: "FWD", img: "https://via.placeholder.com/150?text=Richarlison" },
  { name: "Mbeumo", position: "FWD", img: "https://via.placeholder.com/150?text=Mbeumo" },
  { name: "Bruno", position: "FWD", img: "https://via.placeholder.com/150?text=Bruno" },
  { name: "Rivaldo", position: "FWD", img: "https://via.placeholder.com/150?text=Rivaldo" },
  { name: "Mbappe", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Kylian_Mbapp%C3%A9_2019.jpg/440px-Kylian_Mbapp%C3%A9_2019.jpg" },
  { name: "Haaland", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Erling_Haaland_2023.jpg/440px-Erling_Haaland_2023.jpg" },
  { name: "Yamal", position: "FWD", img: "https://via.placeholder.com/150?text=Yamal" },
  { name: "Ronaldo Nazario", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ronaldo_Lu%C3%ADs_Naz%C3%A1rio_de_Lima_2014_%28cropped%29.jpg/440px-Ronaldo_Lu%C3%ADs_Naz%C3%A1rio_de_Lima_2014_%28cropped%29.jpg" },
  { name: "Ronaldo", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg" },
  { name: "Son", position: "FWD", img: "https://via.placeholder.com/150?text=Son" },
  { name: "Lewandowski", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Robert_Lewandowski_2019.jpg/440px-Robert_Lewandowski_2019.jpg" },
  { name: "Zlatan", position: "FWD", img: "https://via.placeholder.com/150?text=Zlatan" },
  { name: "Ronaldinho", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ronaldinho_2007.jpg/440px-Ronaldinho_2007.jpg" },
  { name: "Neymar", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg/440px-Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg" },
  { name: "Salah", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mohamed_Salah_2018.jpg/440px-Mohamed_Salah_2018.jpg" },
  { name: "Bale", position: "FWD", img: "https://via.placeholder.com/150?text=Bale" },
  { name: "Messi", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg" },
  { name: "Gerd Muller", position: "FWD", img: "https://via.placeholder.com/150?text=Muller" },
  { name: "Henry", position: "FWD", img: "https://via.placeholder.com/150?text=Henry" },
  { name: "Puskas Cole", position: "FWD", img: "https://via.placeholder.com/150?text=Puskas" },
  { name: "Van Basten", position: "FWD", img: "https://via.placeholder.com/150?text=VanBasten" },
  { name: "Romario", position: "FWD", img: "https://via.placeholder.com/150?text=Romario" },
  { name: "Suarez", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Luis_Su%C3%A1rez_2018.jpg/440px-Luis_Su%C3%A1rez_2018.jpg" },
  { name: "Best", position: "FWD", img: "https://via.placeholder.com/150?text=Best" },
  { name: "Batistuta", position: "FWD", img: "https://via.placeholder.com/150?text=Batistuta" },
  { name: "Ruminiegge", position: "FWD", img: "https://via.placeholder.com/150?text=Rummenigge" },
  { name: "Schevchenko", position: "FWD", img: "https://via.placeholder.com/150?text=Shevchenko" },
  { name: "Nistelrooy", position: "FWD", img: "https://via.placeholder.com/150?text=Nistelrooy" },
  { name: "Eto'o", position: "FWD", img: "https://via.placeholder.com/150?text=Etoo" },
  { name: "Drogba", position: "FWD", img: "https://via.placeholder.com/150?text=Drogba" },
  { name: "Benzema", position: "FWD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Karim_Benzema_2018.jpg/440px-Karim_Benzema_2018.jpg" },
  { name: "Rooney", position: "FWD", img: "https://via.placeholder.com/150?text=Rooney" },
  { name: "Fernando Torres", position: "FWD", img: "https://via.placeholder.com/150?text=Torres" },
  { name: "Van Persie", position: "FWD", img: "https://via.placeholder.com/150?text=RVP" },
  { name: "Robben", position: "FWD", img: "https://via.placeholder.com/150?text=Robben" },
  { name: "Ribery", position: "FWD", img: "https://via.placeholder.com/150?text=Ribery" },
  { name: "Owen", position: "FWD", img: "https://via.placeholder.com/150?text=Owen" },
  { name: "Zola", position: "FWD", img: "https://via.placeholder.com/150?text=Zola" },
  { name: "Hazard", position: "FWD", img: "https://via.placeholder.com/150?text=Hazard" },
  { name: "Mane", position: "FWD", img: "https://via.placeholder.com/150?text=Mane" },
  { name: "Di Maria", position: "FWD", img: "https://via.placeholder.com/150?text=DiMaria" },
  { name: "Inzaghi", position: "FWD", img: "https://via.placeholder.com/150?text=Inzaghi" },
  { name: "Crespo", position: "FWD", img: "https://via.placeholder.com/150?text=Crespo" },
  { name: "Sunil Chettri", position: "FWD", img: "https://via.placeholder.com/150?text=Chhetri" },
  { name: "Siva", position: "FWD", img: "https://via.placeholder.com/150?text=Shiva" }
];

module.exports = allPlayers;
